FROM php:8.3.7-fpm

COPY php.ini /usr/local/etc/php/

RUN apt update && apt install -y \
    git \
    curl \
    zip \
    unzip \
    default-mysql-client \
    zlib1g-dev \
    libzip-dev \
    imagemagick libmagickwand-dev \
    && pecl install imagick \
    && docker-php-ext-install pdo_mysql zip \
    && docker-php-ext-enable imagick

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update

WORKDIR /var/www/Rese