FROM php:8.3.7-fpm

RUN apt update && apt install -y \
    cron \
    default-mysql-client \
    zlib1g-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql zip

COPY php.ini /usr/local/etc/php/
COPY cron.root /etc/cron.d/cron

RUN chmod 0644 /etc/cron.d/cron \
    && touch /var/log/cron.log

CMD cron -f